### ISSUE TITLE
Thumb icons

### ISSUE THREAD

**Issue by carletes** [52North/ecmwf-dataset-crawl#28]
Two questions, @noerw:

1. Clicking on the "thumb down" icon does not seem to be working consistently: Sometimes it works and the icon turns red, some other times however it does nothing. Sometimes we (@carletes) feel the red background is a bit lightier (see attachment): ![thumbs-down](https://user-images.githubusercontent.com/1711/43960817-1c200000-9cab-11e8-9c3a-25b37fc04ea7.png) This is what we see on the demo instance. What's the status of this feature in the latest code?
2. Some thumbs-down icons have no red background. Is that perhaps because they were set by the crawler itself? 
![thumbs-down-clear](https://user-images.githubusercontent.com/1711/43960837-2f32d000-9cab-11e8-8396-be666ed4a5e4.png)

**Comment by noerw** [comment]
1. I will look into the logs why it's not working sometimes. (The color is indeed off and fixed in the latest version, but not that's not live yet. The latest version also added a third option "related" for manual classification. We will update the demo on monday)

2. Exactly, the light color indicates the automatic detection by the machine learning model.
When a result was classified manually, the indication is raised.

**Comment by noerw** [comment]
The latest version from `develop` branch is deployed now
